swagger: "2.0"
info:
  title: Simple Crawler
  description: Simple Crawler
  version: 0.0.1
host: localhost
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json

paths:
  /urls:
    post:
      tags:
        - PostCrawlers
      operationId: PostCrawlers
      description: ""
      parameters:
        - $ref: '#/parameters/CrawlerRequest'
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/CrawlerResponse"
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Внутренняя ошибка сервиса
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    required:
      - message
      - code
    description: Error message
    properties:
      message:
        type: string
      code:
        type: integer

  CrawlerResponse:
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string

parameters:
  CrawlerRequest:
    in: body
    name: CrawlerRequest
    schema:
      type: object
      required:
        - urls
      properties:
        urls:
          type: array
          description: "список url"
          items:
            type: string
